gambit {
  tournament {
    gamesPerPairing = 6
  }
  alphaBeta {
    depth1 = 4
    depth2 = 6
  }
  mcts {
    iterations1 = 200
    iterations2 = 500
    explorationConstant = 1.4142135623730951
  }
}