package com.phasmidsoftware.decisiontree.examples.tictactoe

import scala.collection.mutable
import scala.util.Random

/**
  * Matchboxes is the MENACE registry: a mutable map from canonical board value
  * to Matchbox. Canonicalization uses the 8-element dihedral group D4 (4 rotations
  * × 2 for reflection via transpose), so symmetrically equivalent positions share
  * one matchbox and learn together.
  *
  * The canonical form of a board is the minimum `value` over all 8 D4 transforms.
  * (Minimum is arbitrary but deterministic — any fixed choice from the orbit works.)
  *
  * Note: `exchange` (swapping X and O bits) is NOT included in canonicalization here.
  * X always moves first so X-positions and O-positions are structurally distinct in
  * the learning signal. We can revisit this if we want to halve the matchbox count.
  */
class Matchboxes {

  // Canonical board value → Matchbox.
  private val registry: mutable.Map[Int, Matchbox] = mutable.Map.empty

  /**
    * Select a move for the given position.
    * Looks up (or creates) the canonical matchbox, samples a canonical cell,
    * then maps it back to the original board orientation.
    * The returned cell index is in the original orientation and safe to pass
    * directly to TicTacToe.playX / play0.
    *
    * @param ttt    the current TicTacToe state.
    * @param random a Random instance.
    * @return Some(cell) in original orientation, or None if no moves available.
    */

  /** For testing: look up the canonical Matchbox without selecting a move. */
  def get(ttt: TicTacToe): Matchbox = {
    val (canon, transform) = canonicalize(ttt.board)
    registry.getOrElseUpdate(canon, canonicalMatchbox(ttt, transform))
  }

  def selectMove(ttt: TicTacToe, random: Random): Option[Int] = {
    val (canon, transform) = canonicalize(ttt.board)
    val matchbox = registry.getOrElseUpdate(canon, canonicalMatchbox(ttt, transform))
    matchbox.select(random).map { canonCell =>
      // Map canonical cell back to original orientation via the forward transform.
      d4CellPerms(d4InverseIndex(transform))(canonCell)
    }
  }

  /**
    * Update the Matchbox for the given position after a game result.
    * The cell index is in the original orientation (as returned by selectMove).
    *
    * @param ttt    the TicTacToe position at the time the move was made.
    * @param cell   the flat cell index (0..8, row-major) in original orientation.
    * @param result the game result from the perspective of the player who owns this matchbox.
    */
  def update(ttt: TicTacToe, cell: Int, result: MatchResult): Unit = {
    val (canon, transform) = canonicalize(ttt.board)
    val canonCell = transformCell(cell, transform)
    val current = registry.getOrElseUpdate(canon, canonicalMatchbox(ttt, transform))
    val updated = result match {
      case Win  => current.reward(canonCell)
      case Loss => current.penalise(canonCell)
      case Draw => current
    }
    registry(canon) = updated
  }

  /** Number of distinct matchboxes created so far. */
  def size: Int = registry.size

  /** Total beads across all matchboxes (useful for diagnostics). */
  def totalBeads: Int = registry.values.map(_.totalBeads).sum

  // ---------------------------------------------------------------------------
  // D4 canonicalization
  // ---------------------------------------------------------------------------

  /**
    * The 8 D4 transforms as functions on Board value (an Int).
    * Generated by composing rotateBoard (90° CW) and transposeBoard.
    */
  private val d4Transforms: Vector[Int => Int] = {
    import TicTacToeOps.*
    Vector(
      identity,                                                                  // id
      rotateBoard,                                                               // r90
      rotateBoard andThen rotateBoard,                                           // r180
      rotateBoard andThen rotateBoard andThen rotateBoard,                       // r270
      transposeBoard,                                                            // transpose
      transposeBoard andThen rotateBoard,                                        // transpose + r90
      transposeBoard andThen rotateBoard andThen rotateBoard,                    // transpose + r180
      transposeBoard andThen rotateBoard andThen rotateBoard andThen rotateBoard // transpose + r270
    )
  }

  /**
    * Cell permutations derived empirically from the actual d4Transforms.
    * d4CellPerms(i)(cell) = where `cell` lands after applying transform i.
    *
    * Derived by applying each transform to a board with a single X at each cell
    * position and observing where it lands. This guarantees consistency with
    * TicTacToeOps regardless of the exact implementation of rotateBoard/transposeBoard.
    *
    * X at cell i = bit pattern 01 at bits (30 - i*2), so singleX = 1 << (30 - i*2).
    */
  private val d4CellPerms: Vector[Vector[Int]] =
    d4Transforms.map { f =>
      (0 until 9).toVector.map { cell =>
        val singleX = 1 << (30 - cell * 2)
        val transformed = f(singleX)
        (0 until 9).find { i =>
          ((transformed >>> (30 - i * 2)) & 3) != 0
        }.getOrElse(throw new RuntimeException(s"d4CellPerms: no cell found for cell=$cell"))
      }
    }

  /**
    * The inverse index for each D4 transform.
    * id⁻¹=id, r90⁻¹=r270, r180⁻¹=r180, r270⁻¹=r90;
    * all four reflection variants are self-inverse.
    */
  private val d4InverseIndex: Vector[Int] = Vector(0, 3, 2, 1, 4, 5, 6, 7)

  /**
    * Compute the canonical board value and record which transform achieved it.
    * Returns (canonicalValue, transformIndex).
    */
  private def canonicalize(board: Board): (Int, Int) = {
    val orbit = d4Transforms.zipWithIndex.map { case (f, i) => f(board.value) -> i }
    orbit.minBy(_._1)
  }

  /**
    * Map a cell index from original orientation to canonical orientation,
    * by applying the inverse of the transform that produced the canonical form.
    */
  private def transformCell(cell: Int, transformIndex: Int): Int =
    d4CellPerms(d4InverseIndex(transformIndex))(cell)

  /**
    * Create a fresh Matchbox for a position, with open cells expressed in
    * canonical orientation. Ensures matchbox keys and transformCell output
    * are always in the same coordinate space.
    *
    * @param ttt       the TicTacToe position (used to find open cells).
    * @param transform the D4 transform index that maps ttt to its canonical form.
    * @return a new Matchbox keyed by canonical cell indices.
    */
  private def canonicalMatchbox(ttt: TicTacToe, transform: Int): Matchbox = {
    val canonOpen = ttt.open.map { case (r, c) => d4CellPerms(transform)(r * 3 + c) }
    Matchbox(canonOpen)
  }
}

object Matchboxes {
  def apply(): Matchboxes = new Matchboxes()
}

/**
  * The result of a game from one player's perspective.
  */
sealed trait MatchResult
case object Win  extends MatchResult
case object Loss extends MatchResult
case object Draw extends MatchResult